version: '3.8'

services:
  postgres:
    container_name: postgres
    image: 'postgres:14.3'
    volumes:
      - ./postgres:/var/lib/postgres/data
    restart: always
    environment:
      PGDATA: /var/lib/postgres/data
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    env_file:
      - .env
    ports:
      - 5432:5432
    networks:
      - api
  backend:
    container_name: backend
    image: alexcloudstar/chatapp-v2:latest
    ports:
      - '4000:4000'
    volumes:
      - .:/app
      - /app/node_modules
      - /app/prisma
    environment:
      - NODE_ENV=development
    env_file:
      - .env
    links:
      - postgres
    depends_on:
      - postgres
    networks:
      - api

volumes:
  postgres:
networks:
  api:
    driver: bridge
